name: Publish Dev.to Blogs
on: 
    schedule:
        - cron: '0 14 * * *'
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                max_post_count: "3"
                feed_list: "https://dev.to/feed/hriztam"
